// Applaa Theme Presets — 30 youth-oriented themes across 6 genre categories.
// Pi picks a theme name in app-config.ts → entire app transforms.
// Categories: GAMING/TECH | FOOD/LIFESTYLE | AESTHETIC/VIBES | DARK/MOODY | BRIGHT/FUN | ORIGINALS

export const THEMES = {

  // ── ORIGINALS (keep for backward compat) ─────────────────────────────────

  CANDY: {
    gradient: "from-pink-400 via-purple-400 to-indigo-400",
    gradientDark: "from-pink-600 via-purple-600 to-indigo-600",
    primary: "pink",
    primaryClass: "bg-pink-500 hover:bg-pink-600",
    primaryText: "text-pink-600",
    primaryBorder: "border-pink-300",
    primaryLight: "bg-pink-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-pink-200",
    pill: "bg-pink-100 text-pink-700 border-pink-200",
    pillActive: "bg-pink-500 text-white",
    accent: "purple",
  },
  DEEP_SPACE: {
    gradient: "from-slate-900 via-purple-950 to-slate-900",
    gradientDark: "from-slate-950 via-purple-950 to-slate-950",
    primary: "violet",
    primaryClass: "bg-violet-600 hover:bg-violet-700",
    primaryText: "text-violet-400",
    primaryBorder: "border-violet-700",
    primaryLight: "bg-violet-900/50",
    card: "bg-white/8 backdrop-blur-md border border-white/15",
    shadow: "shadow-violet-900",
    pill: "bg-violet-900/60 text-violet-300 border-violet-700",
    pillActive: "bg-violet-600 text-white",
    accent: "indigo",
  },
  JUNGLE: {
    gradient: "from-emerald-400 via-teal-400 to-cyan-500",
    gradientDark: "from-emerald-600 via-teal-600 to-cyan-700",
    primary: "emerald",
    primaryClass: "bg-emerald-500 hover:bg-emerald-600",
    primaryText: "text-emerald-700",
    primaryBorder: "border-emerald-300",
    primaryLight: "bg-emerald-100",
    card: "bg-white/90",
    shadow: "shadow-emerald-200",
    pill: "bg-emerald-100 text-emerald-700 border-emerald-200",
    pillActive: "bg-emerald-500 text-white",
    accent: "teal",
  },
  FIRE: {
    gradient: "from-red-500 via-orange-400 to-yellow-400",
    gradientDark: "from-red-700 via-orange-600 to-yellow-500",
    primary: "orange",
    primaryClass: "bg-orange-500 hover:bg-orange-600",
    primaryText: "text-orange-700",
    primaryBorder: "border-orange-300",
    primaryLight: "bg-orange-100",
    card: "bg-white/90",
    shadow: "shadow-orange-200",
    pill: "bg-orange-100 text-orange-700 border-orange-200",
    pillActive: "bg-orange-500 text-white",
    accent: "red",
  },
  OCEAN: {
    gradient: "from-blue-500 via-cyan-400 to-teal-400",
    gradientDark: "from-blue-700 via-cyan-600 to-teal-600",
    primary: "cyan",
    primaryClass: "bg-cyan-500 hover:bg-cyan-600",
    primaryText: "text-cyan-700",
    primaryBorder: "border-cyan-300",
    primaryLight: "bg-cyan-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-cyan-200",
    pill: "bg-cyan-100 text-cyan-700 border-cyan-200",
    pillActive: "bg-cyan-500 text-white",
    accent: "blue",
  },
  NEON: {
    gradient: "from-gray-950 via-gray-900 to-gray-950",
    gradientDark: "from-black via-gray-950 to-black",
    primary: "lime",
    primaryClass: "bg-lime-500 hover:bg-lime-400",
    primaryText: "text-lime-400",
    primaryBorder: "border-lime-500",
    primaryLight: "bg-lime-950",
    card: "bg-gray-900 border border-lime-500/30 shadow-lime-500/10",
    shadow: "shadow-lime-500/20",
    pill: "bg-lime-950 text-lime-400 border-lime-700",
    pillActive: "bg-lime-500 text-gray-950",
    accent: "yellow",
  },
  SUNSET: {
    gradient: "from-yellow-400 via-orange-400 to-pink-500",
    gradientDark: "from-yellow-500 via-orange-500 to-pink-600",
    primary: "amber",
    primaryClass: "bg-amber-500 hover:bg-amber-600",
    primaryText: "text-amber-700",
    primaryBorder: "border-amber-300",
    primaryLight: "bg-amber-100",
    card: "bg-white/90",
    shadow: "shadow-amber-200",
    pill: "bg-amber-100 text-amber-700 border-amber-200",
    pillActive: "bg-amber-500 text-white",
    accent: "orange",
  },
  ICE: {
    gradient: "from-sky-200 via-blue-100 to-indigo-200",
    gradientDark: "from-sky-400 via-blue-300 to-indigo-400",
    primary: "sky",
    primaryClass: "bg-sky-500 hover:bg-sky-600",
    primaryText: "text-sky-700",
    primaryBorder: "border-sky-300",
    primaryLight: "bg-sky-100",
    card: "bg-white/75 backdrop-blur-sm",
    shadow: "shadow-sky-200",
    pill: "bg-sky-100 text-sky-700 border-sky-200",
    pillActive: "bg-sky-500 text-white",
    accent: "indigo",
  },

  // ── GAMING & TECH ─────────────────────────────────────────────────────────

  PIXEL_NEON: {
    // Dark purple + neon violet — gaming / esports vibe
    gradient: "from-gray-900 via-purple-950 to-gray-900",
    gradientDark: "from-black via-purple-950 to-black",
    primary: "violet",
    primaryClass: "bg-violet-500 hover:bg-violet-400",
    primaryText: "text-violet-400",
    primaryBorder: "border-violet-500",
    primaryLight: "bg-violet-900/30",
    card: "bg-gray-800/80 backdrop-blur-xl border border-violet-500/30",
    shadow: "shadow-violet-500/20",
    pill: "bg-gray-700 text-gray-300 border-gray-600",
    pillActive: "bg-violet-500 text-white",
    accent: "cyan",
  },
  ARCADE: {
    // Dark slate + red — retro arcade / fighting game energy
    gradient: "from-slate-900 via-red-950 to-slate-900",
    gradientDark: "from-black via-red-950 to-black",
    primary: "red",
    primaryClass: "bg-red-500 hover:bg-red-400",
    primaryText: "text-red-400",
    primaryBorder: "border-red-500",
    primaryLight: "bg-red-900/30",
    card: "bg-slate-800/80 backdrop-blur-xl border border-red-500/20",
    shadow: "shadow-red-500/20",
    pill: "bg-slate-700 text-slate-300 border-slate-600",
    pillActive: "bg-red-500 text-white",
    accent: "orange",
  },
  MATRIX: {
    // Black + lime green — hacker / coding / tech vibe
    gradient: "from-black via-green-950 to-black",
    gradientDark: "from-black via-green-950 to-black",
    primary: "green",
    primaryClass: "bg-green-500 hover:bg-green-400",
    primaryText: "text-green-400",
    primaryBorder: "border-green-500",
    primaryLight: "bg-green-900/30",
    card: "bg-black/80 backdrop-blur-xl border border-green-500/30",
    shadow: "shadow-green-500/20",
    pill: "bg-gray-900 text-green-300 border-green-800",
    pillActive: "bg-green-500 text-black font-bold",
    accent: "emerald",
  },
  RETROWAVE: {
    // Purple/fuchsia/indigo — synthwave / 80s / lo-fi beats
    gradient: "from-purple-900 via-fuchsia-900 to-indigo-900",
    gradientDark: "from-purple-950 via-fuchsia-950 to-indigo-950",
    primary: "fuchsia",
    primaryClass: "bg-fuchsia-500 hover:bg-fuchsia-400",
    primaryText: "text-fuchsia-400",
    primaryBorder: "border-fuchsia-500",
    primaryLight: "bg-fuchsia-900/30",
    card: "bg-purple-900/70 backdrop-blur-xl border border-fuchsia-500/30",
    shadow: "shadow-fuchsia-500/20",
    pill: "bg-purple-800 text-purple-200 border-purple-700",
    pillActive: "bg-fuchsia-500 text-white",
    accent: "pink",
  },
  HOLOGRAM: {
    // Dark slate + cyan — sci-fi / futuristic / AR vibe
    gradient: "from-slate-900 via-cyan-950 to-slate-900",
    gradientDark: "from-black via-cyan-950 to-black",
    primary: "cyan",
    primaryClass: "bg-cyan-500 hover:bg-cyan-400",
    primaryText: "text-cyan-400",
    primaryBorder: "border-cyan-500",
    primaryLight: "bg-cyan-900/30",
    card: "bg-slate-800/80 backdrop-blur-xl border border-cyan-400/20",
    shadow: "shadow-cyan-400/20",
    pill: "bg-slate-700 text-slate-300 border-slate-600",
    pillActive: "bg-cyan-500 text-black font-bold",
    accent: "teal",
  },

  // ── FOOD & LIFESTYLE ──────────────────────────────────────────────────────

  MATCHA: {
    // Soft green + cream — cafe / cozy / healthy vibe
    gradient: "from-green-200 via-emerald-300 to-teal-200",
    gradientDark: "from-green-400 via-emerald-500 to-teal-400",
    primary: "emerald",
    primaryClass: "bg-emerald-600 hover:bg-emerald-700",
    primaryText: "text-emerald-700",
    primaryBorder: "border-emerald-400",
    primaryLight: "bg-emerald-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-emerald-200",
    pill: "bg-emerald-100 text-emerald-700 border-emerald-200",
    pillActive: "bg-emerald-600 text-white",
    accent: "teal",
  },
  BERRY: {
    // Purple/fuchsia/pink — sweet / dessert / aesthetic food
    gradient: "from-purple-400 via-fuchsia-400 to-pink-400",
    gradientDark: "from-purple-600 via-fuchsia-600 to-pink-600",
    primary: "purple",
    primaryClass: "bg-purple-600 hover:bg-purple-700",
    primaryText: "text-purple-700",
    primaryBorder: "border-purple-400",
    primaryLight: "bg-purple-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-purple-200",
    pill: "bg-purple-100 text-purple-700 border-purple-200",
    pillActive: "bg-purple-600 text-white",
    accent: "pink",
  },
  TOMATO: {
    // Red/orange/amber — recipe / food blog / cooking vibe
    gradient: "from-red-400 via-orange-400 to-amber-400",
    gradientDark: "from-red-600 via-orange-600 to-amber-500",
    primary: "red",
    primaryClass: "bg-red-600 hover:bg-red-700",
    primaryText: "text-red-700",
    primaryBorder: "border-red-400",
    primaryLight: "bg-red-100",
    card: "bg-white/90",
    shadow: "shadow-orange-200",
    pill: "bg-orange-100 text-orange-700 border-orange-200",
    pillActive: "bg-red-600 text-white",
    accent: "orange",
  },
  LEMONADE: {
    // Yellow/lime/green — fresh / summer / drinks vibe
    gradient: "from-yellow-300 via-lime-300 to-green-300",
    gradientDark: "from-yellow-500 via-lime-500 to-green-400",
    primary: "yellow",
    primaryClass: "bg-yellow-500 hover:bg-yellow-600",
    primaryText: "text-yellow-700",
    primaryBorder: "border-yellow-400",
    primaryLight: "bg-yellow-100",
    card: "bg-white/90",
    shadow: "shadow-yellow-200",
    pill: "bg-lime-100 text-lime-700 border-lime-200",
    pillActive: "bg-yellow-500 text-white",
    accent: "lime",
  },
  COCOA: {
    // Warm amber/orange dark — hot chocolate / coffee / cozy dark
    gradient: "from-amber-700 via-orange-800 to-amber-800",
    gradientDark: "from-amber-800 via-orange-900 to-stone-900",
    primary: "amber",
    primaryClass: "bg-amber-500 hover:bg-amber-400",
    primaryText: "text-amber-200",
    primaryBorder: "border-amber-500",
    primaryLight: "bg-amber-900/30",
    card: "bg-amber-900/70 backdrop-blur-xl border border-amber-600/30",
    shadow: "shadow-amber-700/30",
    pill: "bg-amber-800 text-amber-200 border-amber-700",
    pillActive: "bg-amber-500 text-white",
    accent: "orange",
  },

  // ── AESTHETIC VIBES ───────────────────────────────────────────────────────

  SAKURA: {
    // Soft pink/rose — kawaii / cute / Japanese aesthetic
    gradient: "from-pink-200 via-rose-200 to-pink-300",
    gradientDark: "from-pink-400 via-rose-400 to-pink-500",
    primary: "pink",
    primaryClass: "bg-pink-500 hover:bg-pink-600",
    primaryText: "text-pink-600",
    primaryBorder: "border-pink-300",
    primaryLight: "bg-pink-100",
    card: "bg-white/90 backdrop-blur-sm",
    shadow: "shadow-pink-200",
    pill: "bg-pink-100 text-pink-600 border-pink-200",
    pillActive: "bg-pink-500 text-white",
    accent: "rose",
  },
  COTTAGECORE: {
    // Amber/yellow/green — earthy / botanical / nature / vintage
    gradient: "from-amber-200 via-yellow-200 to-green-200",
    gradientDark: "from-amber-400 via-yellow-400 to-green-400",
    primary: "amber",
    primaryClass: "bg-amber-600 hover:bg-amber-700",
    primaryText: "text-amber-800",
    primaryBorder: "border-amber-400",
    primaryLight: "bg-amber-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-amber-200",
    pill: "bg-green-100 text-green-700 border-green-200",
    pillActive: "bg-amber-600 text-white",
    accent: "green",
  },
  VAPORWAVE: {
    // Pink/purple/indigo dark — retro-futuristic / 80s neon aesthetic
    gradient: "from-pink-600 via-purple-700 to-indigo-700",
    gradientDark: "from-pink-800 via-purple-900 to-indigo-900",
    primary: "pink",
    primaryClass: "bg-pink-500 hover:bg-pink-400",
    primaryText: "text-pink-300",
    primaryBorder: "border-pink-400",
    primaryLight: "bg-pink-900/30",
    card: "bg-purple-900/70 backdrop-blur-xl border border-pink-400/30",
    shadow: "shadow-pink-500/20",
    pill: "bg-purple-800 text-purple-200 border-purple-700",
    pillActive: "bg-pink-500 text-white",
    accent: "cyan",
  },
  Y2K: {
    // Sky/pink/purple light — early 2000s nostalgia / chrome / butterfly
    gradient: "from-sky-200 via-pink-200 to-purple-200",
    gradientDark: "from-sky-400 via-pink-400 to-purple-400",
    primary: "sky",
    primaryClass: "bg-sky-500 hover:bg-sky-600",
    primaryText: "text-sky-600",
    primaryBorder: "border-sky-300",
    primaryLight: "bg-sky-100",
    card: "bg-white/90 backdrop-blur-sm",
    shadow: "shadow-sky-200",
    pill: "bg-sky-100 text-sky-600 border-sky-200",
    pillActive: "bg-sky-500 text-white",
    accent: "pink",
  },
  BUBBLEGUM: {
    // Hot pink/fuchsia/rose — playful / fun / pop / maximalist
    gradient: "from-pink-400 via-fuchsia-400 to-rose-400",
    gradientDark: "from-pink-600 via-fuchsia-600 to-rose-600",
    primary: "fuchsia",
    primaryClass: "bg-fuchsia-600 hover:bg-fuchsia-700",
    primaryText: "text-fuchsia-700",
    primaryBorder: "border-fuchsia-400",
    primaryLight: "bg-fuchsia-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-fuchsia-200",
    pill: "bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200",
    pillActive: "bg-fuchsia-600 text-white",
    accent: "rose",
  },

  // ── DARK & MOODY ──────────────────────────────────────────────────────────

  DARK_ACADEMIA: {
    // Stone/amber dark — scholarly / moody / bookworm / literary
    gradient: "from-stone-800 via-amber-950 to-stone-900",
    gradientDark: "from-stone-900 via-amber-950 to-stone-950",
    primary: "amber",
    primaryClass: "bg-amber-500 hover:bg-amber-400",
    primaryText: "text-amber-400",
    primaryBorder: "border-amber-600",
    primaryLight: "bg-amber-900/30",
    card: "bg-stone-800/80 backdrop-blur-xl border border-amber-700/30",
    shadow: "shadow-amber-700/20",
    pill: "bg-stone-700 text-stone-300 border-stone-600",
    pillActive: "bg-amber-500 text-stone-900 font-bold",
    accent: "yellow",
  },
  MIDNIGHT: {
    // Slate/blue/indigo dark — night owl / late study / calm focus
    gradient: "from-slate-900 via-blue-950 to-indigo-950",
    gradientDark: "from-slate-950 via-blue-950 to-indigo-950",
    primary: "blue",
    primaryClass: "bg-blue-500 hover:bg-blue-400",
    primaryText: "text-blue-400",
    primaryBorder: "border-blue-600",
    primaryLight: "bg-blue-900/30",
    card: "bg-slate-800/80 backdrop-blur-xl border border-blue-600/20",
    shadow: "shadow-blue-500/20",
    pill: "bg-slate-700 text-slate-300 border-slate-600",
    pillActive: "bg-blue-500 text-white",
    accent: "indigo",
  },
  OBSIDIAN: {
    // Black/zinc + gold — premium / luxury / sleek dark
    gradient: "from-neutral-900 via-stone-900 to-zinc-900",
    gradientDark: "from-black via-stone-950 to-zinc-950",
    primary: "amber",
    primaryClass: "bg-amber-400 hover:bg-amber-300",
    primaryText: "text-amber-400",
    primaryBorder: "border-amber-500/50",
    primaryLight: "bg-amber-900/20",
    card: "bg-zinc-800/80 backdrop-blur-xl border border-amber-400/20",
    shadow: "shadow-amber-400/15",
    pill: "bg-zinc-700 text-zinc-300 border-zinc-600",
    pillActive: "bg-amber-400 text-black font-bold",
    accent: "yellow",
  },

  // ── BRIGHT & FUN ──────────────────────────────────────────────────────────

  SUNSHINE: {
    // Yellow/orange/amber — happy / cheerful / uplifting
    gradient: "from-yellow-300 via-orange-300 to-amber-300",
    gradientDark: "from-yellow-500 via-orange-400 to-amber-500",
    primary: "orange",
    primaryClass: "bg-orange-500 hover:bg-orange-600",
    primaryText: "text-orange-700",
    primaryBorder: "border-orange-400",
    primaryLight: "bg-orange-100",
    card: "bg-white/90",
    shadow: "shadow-orange-200",
    pill: "bg-orange-100 text-orange-700 border-orange-200",
    pillActive: "bg-orange-500 text-white",
    accent: "yellow",
  },
  TROPICAL: {
    // Teal/cyan/blue — beach / summer / island holiday
    gradient: "from-teal-400 via-cyan-400 to-blue-400",
    gradientDark: "from-teal-600 via-cyan-600 to-blue-600",
    primary: "teal",
    primaryClass: "bg-teal-600 hover:bg-teal-700",
    primaryText: "text-teal-700",
    primaryBorder: "border-teal-400",
    primaryLight: "bg-teal-100",
    card: "bg-white/85 backdrop-blur-sm",
    shadow: "shadow-teal-200",
    pill: "bg-teal-100 text-teal-700 border-teal-200",
    pillActive: "bg-teal-600 text-white",
    accent: "cyan",
  },
  CARNIVAL: {
    // Red/yellow/green — festive / party / celebrations
    gradient: "from-red-400 via-yellow-400 to-green-400",
    gradientDark: "from-red-600 via-yellow-500 to-green-500",
    primary: "red",
    primaryClass: "bg-red-600 hover:bg-red-700",
    primaryText: "text-red-700",
    primaryBorder: "border-red-400",
    primaryLight: "bg-red-100",
    card: "bg-white/90",
    shadow: "shadow-red-200",
    pill: "bg-yellow-100 text-yellow-800 border-yellow-200",
    pillActive: "bg-red-600 text-white",
    accent: "orange",
  },

} as const;

export type ThemeName = keyof typeof THEMES;
export type Theme = typeof THEMES[ThemeName];
